#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openstackdocstheme
Version  : 1.27.1
Release  : 23
URL      : https://files.pythonhosted.org/packages/86/ad/b01371d606adab45c1e88eae12a9aabf3b1042ab00a5b0252e41f5882d38/openstackdocstheme-1.27.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/86/ad/b01371d606adab45c1e88eae12a9aabf3b1042ab00a5b0252e41f5882d38/openstackdocstheme-1.27.1.tar.gz
Summary  : OpenStack Docs Theme
Group    : Development/Tools
License  : Apache-2.0
Requires: openstackdocstheme-license = %{version}-%{release}
Requires: openstackdocstheme-python = %{version}-%{release}
Requires: openstackdocstheme-python3 = %{version}-%{release}
Requires: dulwich
Requires: os-api-ref
Requires: pbr
Requires: reno
BuildRequires : buildreq-distutils3
BuildRequires : dulwich
BuildRequires : pbr

%description
Team and repository tags
        ========================

%package license
Summary: license components for the openstackdocstheme package.
Group: Default

%description license
license components for the openstackdocstheme package.


%package python
Summary: python components for the openstackdocstheme package.
Group: Default
Requires: openstackdocstheme-python3 = %{version}-%{release}

%description python
python components for the openstackdocstheme package.


%package python3
Summary: python3 components for the openstackdocstheme package.
Group: Default
Requires: python3-core

%description python3
python3 components for the openstackdocstheme package.


%prep
%setup -q -n openstackdocstheme-1.27.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540463179
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openstackdocstheme
cp LICENSE %{buildroot}/usr/share/package-licenses/openstackdocstheme/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openstackdocstheme/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
